In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/processed/recipes_documents.csv")

In [3]:
df.head()

,name,description,ingredients,steps,tags,minutes,document
0,arriba baked winter squash mexican style,autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...","['make a choice and proceed with recipe', 'dep...","['60-minutes-or-less', 'time-to-make', 'course...",55,\nRecipe Name: arriba baked winter squash me...
1,a bit different breakfast pizza,this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...","['preheat oven to 425 degrees f', 'press dough...","['30-minutes-or-less', 'time-to-make', 'course...",30,\nRecipe Name: a bit different breakfast pizz...
2,all in the kitchen chili,this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...","['brown ground beef in large pot', 'add choppe...","['time-to-make', 'course', 'preparation', 'mai...",130,\nRecipe Name: all in the kitchen chili\n\nDe...
3,alouette potatoes,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",['place potatoes in a large pot of lightly sal...,"['60-minutes-or-less', 'time-to-make', 'course...",45,\nRecipe Name: alouette potatoes\n\nDescripti...
4,amish tomato ketchup for canning,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",['mix all ingredients& boil for 2 1 / 2 hours ...,"['weeknight', 'time-to-make', 'course', 'main-...",190,\nRecipe Name: amish tomato ketchup for cann...

In [4]:
!python -m pip install minsearch

Requirement already satisfied: minsearch in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (0.2.0)
Requirement already satisfied: numpy in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from minsearch) (2.5.1)
Requirement already satisfied: pandas in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from minsearch) (3.0.3)
Requirement already satisfied: scikit-learn in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from minsearch) (1.9.0)
Requirement already satisfied: stemlite>=0.1.0 in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from minsearch) (0.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from pandas->minsearch) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from pandas->minsearch) (2026.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from scikit-learn->minsearch) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from scikit-learn->minsearch) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from scikit-learn->minsearch) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from scikit-learn->minsearch) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\desktop\kitchen-assistant\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->minsearch) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import minsearch
import pandas as pd

In [6]:
df=pd.read_csv("../data/processed/recipes_documents.csv")

In [7]:
df.head()

,name,description,ingredients,steps,tags,minutes,document
0,arriba baked winter squash mexican style,autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...","['make a choice and proceed with recipe', 'dep...","['60-minutes-or-less', 'time-to-make', 'course...",55,\nRecipe Name: arriba baked winter squash me...
1,a bit different breakfast pizza,this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...","['preheat oven to 425 degrees f', 'press dough...","['30-minutes-or-less', 'time-to-make', 'course...",30,\nRecipe Name: a bit different breakfast pizz...
2,all in the kitchen chili,this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...","['brown ground beef in large pot', 'add choppe...","['time-to-make', 'course', 'preparation', 'mai...",130,\nRecipe Name: all in the kitchen chili\n\nDe...
3,alouette potatoes,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",['place potatoes in a large pot of lightly sal...,"['60-minutes-or-less', 'time-to-make', 'course...",45,\nRecipe Name: alouette potatoes\n\nDescripti...
4,amish tomato ketchup for canning,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",['mix all ingredients& boil for 2 1 / 2 hours ...,"['weeknight', 'time-to-make', 'course', 'main-...",190,\nRecipe Name: amish tomato ketchup for cann...

In [8]:
text_fields=[
    "documents"
]
keyword_fields=[
    "name"
]

In [9]:
index = minsearch.Index(
    text_fields=text_fields,
    keyword_fields=keyword_fields
)

In [10]:
index.fit(df.to_dict(orient="records"))

In [11]:
results = index.search(
    query="vegetarian mexican squash",
    num_results=5
)

results

[]